InterMilan/InterMilan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),
    path('',include('todo.urls'))
]

InterMilan/client/urls.py
from .imports import *

app_name = 'client'



urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('home/', home, name='home'),
    path('edit/',edit_profile, name='edit_profile'),
    path('logout/',logout_view,name= 'logout'),

]

InterMilan/todo/urls.py
from .imports import *
from .views.client_tasks import client_tasks

app_name = 'todo'

urlpatterns = [

    path('task/',tasks_manager, name='tasks'),
    path('mmd/<int:id>',client_tasks,name = 'client_tasks')

]

InterMilan/client/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
class CustomUser(AbstractUser):
    cellphone = models.CharField(max_length=10, null=True, blank=True)

InterMilan/todo/models.py
from client.models import CustomUser
from django.db import models


class Task(models.Model):
    username = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    title = models.CharField(max_length=200,null=True,blank=True)
    done = models.BooleanField(default=False)

    def checked(self):
        self.done = True
        self.save()

#dfdsdfd
    def unchecked(self):
        self.done = False
        self.save()

InterMilan/client/views/edit_profile.py
from client.imports import *
from client.models import CustomUser


@login_required
def edit_profile(request):
    if request.method == 'POST':
        # username = request.POST.get('username_new')
        firstname = request.POST.get('firstname')
        lastname  = request.POST.get('lastname')
        cellphone = request.POST.get('cellphone')
        user = CustomUser.objects.get(id=request.user.id)
        user.first_name = firstname
        user.last_name = lastname
        user.cellphone = cellphone
        user.save()
        return redirect(reverse('client:home'))


    else:
        return render(request, 'edit_profile.html')

InterMilan/client/views/home.py
from ..imports import *
from todo.models import Task
from ..models import CustomUser


@login_required
def home(request):
    context={}

    if request.user.is_superuser:
        context['users'] = CustomUser.objects.filter()







    if request.method=='POST':

        title = request.POST.get('input')

        task = Task()
        task.title = title
        task.username = request.user
        task.save()
    context['mmd'] = Task.objects.filter(username=request.user).order_by('-id')[:4]










    # Task.objects.filter(some_field=).delete()

    return render(request, 'home.html', context)

InterMilan/client/views/login_view.py
from client.imports import *


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse('client:home'))
    return render(request, 'logi
    
    
    
    
    
    
    
    
    
    
    Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyNTE0MDIwLCJpYXQiOjE2OTI0Mjc2MjAsImp0aSI6IjRkMDljMWNmMmVkMjQxZDZiODQ4N2ExNGJlODk5ZWM1IiwidXNlcl9pZCI6Mn0.iZg-iLEUOi15GvkdKim7Zn7tO35i2ZXIF_nmoM-4pMo

InterMilan/client/views/logout.py
from client.imports import *


def logout_view(request):
    logout(request)
    return redirect(reverse('client:login'))

InterMilan/client/views/register.py
from client.models import *
from ..imports import *
import re


def register(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        if CustomUser.objects.filter(username=username).exists():
            context['error'] = True
            context['error_msg'] = 'Username has exist!!!'
        else:
            user = CustomUser(username=username)
            regex = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
            if re.fullmatch(regex, email):
                user.email = email
                user.set_password(password)
                user.save()
                return redirect(reverse('client:login'))
            else:
                context['error_msg'] = "email is invalid!!!!"
    return render(request, 'register.html', context)

InterMilan/todo/views/client_tasks.py
from todo.imports import *
from todo.models import Task


def client_tasks(request,id):
    if request.user.is_superuser:
        context ={}
        context['mmdjavad'] = Task.objects.filter(username=id)


        return render(request,'tasks.html',context)

    return redirect(reverse('client:home'))

InterMilan/todo/views/task_manager.py
from todo.imports import *
from todo.models import Task


# Create your views here.


def tasks_manager(request):
    context = {}
    if request.method=='POST':
        title = request.POST.get('input')
        task = Task()
        task.title = title
        task.username = request.user
        task.save()
    elif request.method == 'GET':
        try:
            if 'delete' in request.GET:
                t = Task.objects.get(id=request.GET.get('delete'), username=request.user)
                t.delete()
                context['msg'] = 'delete done!'
                return redirect(reverse('todo:tasks'))
            if 'check' in request.GET:
                t = Task.objects.get(id=request.GET.get('check'), username=request.user)
                t.checked()
                context['msg'] = 'check done!'
                return redirect(reverse('todo:tasks'))
            else:
                t = Task.objects.get(id=request.GET.get('uncheck'), username=request.user)
                t.unchecked()
                context['msg'] = 'uncheck done!'
                return redirect(reverse('todo:tasks'))


        except:
            pass
    context['mmd'] = Task.objects.filter(username=request.user).order_by('-id')
    return render(request, 'tasks.html', context)

InterMilan/templates/base.html
<!DOCTYPE html>

<head>
  <title>My App</title>

    <style>
        body{
    background-size: cover;



    height: 100vh;
    padding:0;
    margin:0;
}
        button{
            width: 150px;
            margin-top: 20px;
            height: 40px;
            color: #000000;
            background: #69ff69;
            margin-left: 60px;
            border-radius: 15px;

        }
        .second {
            width: 150px;
            height: 35px;
            background: #d0c9c9;
            margin-top: 25px;
            border: 2px solid black;
            border-radius: 15px;
            margin-left: 600px;
        }
        .second  a{

            text-decoration: none;
            font-size: 25px;
            margin-left: 40px;
            color: black;


        }
        .ff input{
            width: 200px;
            height: 35px;
            border-radius: 15px;
            font-size: 17px;
        }

        a{
            text-decoration: none;
            color: black;
            border: 1px solid black;
            border-radius: 15px;
        }

        .menu{
            display: flex;
            padding: 10px;
            gap: 40px;
        }



    </style>
</head>
<body>
  <div>
    {% block content %}
    {% endblock %}
  </div>
</body>

InterMilan/templates/base2.html
<head>
    <style>
        body {
  font-family: Arial, sans-serif;
}

h1 {
  text-align: center;
}

ul {
  list-style: none;


}
ul li{


}

li {
  align-items: center;
  margin: 10px 0;
  padding: 10px;
  display: flex;
}
.ssr{
      border: 3px solid #ddd;
  border-radius: 5px;
    display: flex;
    padding: 10px;
    margin-bottom: 15px;
}
.slide{
    text-decoration: none;
}
.slide li{
    background-color: #c886da;
}
.ssr.done{
    background-color: #3e8a3e;
}

.check{
    color: yellowgreen;
    font-size: 55px;
    float: right;
}
.labelasli{
    width: 60px;
    margin: auto;
}
.label{
    margin-top: 20px;
    color: #345b7a;
}
li input[type="checkbox"] {
    color: red;
}

.delete-button {
  margin-left: auto;
  background-color: #ffffff;
  color: #ff0000;
  border: 2px solid red;
  border-radius: 50rem;
  padding: 5px 10px;
  cursor: pointer;
}

.delete-button:hover {
  background-color: #e79696;
}

form {
  display: flex;
  margin-top: 20px;
}

form input[type="text"] {
  flex: 1;
  padding: 10px;
  border: none;
  border-radius: 50px;
  margin-right: 10px;
}

form button {
  background-color: #4CAF50;
  color: white;
  border: none;
  border-radius: 50px;
  padding: 10px;
  cursor: pointer;
}

form button:hover {
  background-color: #3e8e41;
}
    </style>
</head>
<body>
{% block content %}

{% endblock %}
</body>

InterMilan/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>ویرایش پروفایل</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        <label for="a">username</label>
        <input type="text" id="a" name="username_new" value="{{ user.username }}">
        <br>
        <br>
        <label for="b">firstname</label>
        <input type="text" id="b" name="firstname" placeholder="optional" value="{{ user.first_name }}">
        <br>
        <br>
        <label for="c">lastname</label>
        <input type="text" id="c" name="lastname" placeholder="optional" value="{{ user.last_name }}">
        <br>
        <br>
        <label for="d">cellphone</label>
        <input type="text" id="d" name="cellphone" placeholder="optional" value="{{ user.cellphone }}">
        <br>
        <br>
        <button type="submit">save</button>
    </form>
{% endblock %}

InterMilan/templates/home.html
{% extends 'base2.html' %}


{% block content %}

    <div class="menu">
        <h2>خانه</h2>
        <p>خوش‌آمدید{{ user.username }}</p>
        <a href="{% url 'client:edit_profile' %}">ویرایش پروفایل</a>
        <br>
        <br>
        <a href="{% url 'client:logout' %}">logout</a>
    </div>


    <form action="" method="post">
        {% csrf_token %}
        <div id="myDIV" class="header">
            <h2 style="margin:5px">My To Do List</h2>
            <label for="myInput"><input type="text" id="myInput" placeholder="Title..." name="input">
            </label>
            <button type="submit" class="addBtn">ADD</button>
        </div>


    </form>
    <ul id="myUL">
        {% for m in mmd %}
            <li>{{ m.title }}</li>
        {% endfor %}

    </ul>
    <div style="padding: 50px"><a style="margin-left: 300px" href="{% url 'todo:tasks' %} ">ALL TASKS</a>
    </div>



    <ul>


        <div>
            {% for s in users %}
                <a class="slide" href="{% url 'todo:client_tasks' s.id %}?todo={{ s.id }} ">
                    <li>{{ s.username }}</li>
                </a></div>
            {% endfor %}

    </ul>



{% endblock %}

InterMilan/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>ورود</h2>
    <div class="ff">
        <form method="post">
            {% csrf_token %}
            <label for="username">نام کاربری:
                <input type="text" name="username" required id="username">
            </label>
            <br>
            <br>
            <label for="password">رمز عبور:
                <input type="password" name="password" required id="password">
            </label>
            <br>
            <button type="submit">ورود</button>
            <div class="second"><a href="{% url 'client:register' %}">register</a></div>


        </form>
    </div>
{% endblock %}

InterMilan/templates/register.html
{% extends 'base.html' %}

{% block content %}
    {% if error %}
        <div style="padding: 1rem;background-color: red;">
            <h3>خطا</h3>
            <span>{{ error_msg }}</span>
        </div>
    {% endif %}
    <h1 style="margin-left: 600px">signup</h1>
    <div class="ff">
        <form method="post" style="margin-top: 50px">
            {% csrf_token %}
            <label for="a" style="margin-left: 500px">username:
                <input type="text" id="a" name="username">
            </label>
            <br>
            <br>
            <label for="b" style="margin-left: 500px">email:
                <input type="email" id="b" name="email" style="margin-left: 25px">
            </label>
            <br>
            <br>
            <label for="c" style="margin-left: 500px">password:
                <input type="password" id="c" name="password">
            </label>
            <br>

            <button type="submit" style="margin-left: 600px">register</button>
            <div class="second"><a href="{% url 'client:edit_profile' %}">login</a></div>
        </form>
    </div>
    <p>{{ error_msg }}</p>
{% endblock %}

InterMilan/templates/tasks.html
{% extends 'base2.html' %}


{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <div id="myDIV" class="header">
            <h2 style="margin:5px">My To Do List</h2>
            <label for="myInput"><input type="text" id="myInput" placeholder="Title..." name="input">
            </label>
            <button type="submit" class="addBtn">ADD</button>
        </div>


    </form>

    {% if msg %}
        <h3>{{ msg }}</h3>
    {% endif %}
    <ul id="todo-list">
        {% for m in mmd %}
            <div class="ssr {% if m.done %}done{% endif %}">
                <li>{{ m.title }}</li>
                <div class="labelasli">
                    {% if not m.done %}
                        <a href="{% url 'todo:tasks' %}?check={{ m.id }}">
                            <button type="submit">finish task</button>
                        </a>
                    {% else %}
                        <a href="{% url 'todo:tasks' %}?uncheck={{ m.id }}">
                            <button type="submit">undo task</button>
                        </a>
                    {% endif %}
                </div>
                <a href="{% url 'todo:tasks' %}?delete={{ m.id }}">
                    <button class="delete-button">Delete</button>
                </a>
            </div>
        {% endfor %}

    </ul>


    {%for mmd in mmdjavad  %}
        <ul>
        <li>{{ mmd.title }}</li>
        </ul>

    {% endfor %}




    <a style="margin-left: 45px" href="{% url 'client:home' %}">BACK</a>

{% endblock %}